In [49]:
import pandas as pd
import openpyxl

In [50]:
pd.set_option('display.max_columns', None)

In [51]:
%cd drive/MyDrive/verif_tonnage/source

[WinError 3] Le chemin d’accès spécifié est introuvable: 'drive/MyDrive/verif_tonnage/source'
c:\Users\amine.saadeddine\Documents\projets\verif_tonnage_valene

In [52]:
%ls

 Le volume dans le lecteur C s'appelle Windows
 Le num�ro de s�rie du volume est 1CBC-0FC1

 R�pertoire de c:\Users\amine.saadeddine\Documents\projets\verif_tonnage_valene

15/12/2025  12:27    <DIR>          .
15/12/2025  11:42    <DIR>          ..
12/12/2025  15:21    <DIR>          build
12/12/2025  15:23        44�859�733 controle_tonnage_valene.exe
15/12/2025  09:10    <DIR>          corrige
15/12/2025  11:28    <DIR>          dist
12/12/2025  15:45             6�151 main.py
12/12/2025  15:21               695 main.spec
15/12/2025  11:42    <DIR>          output
12/12/2025  16:56             4�350 README.md
15/12/2025  12:25    <DIR>          source
15/12/2025  12:27            28�002 test.xlsx
15/12/2025  14:21           149�902 verif_tonnage.ipynb
15/12/2025  12:27            40�078 verif_tonnage_resultat.csv
               7 fichier(s)       45�088�911 octets
               7 R�p(s)  162�713�522�176 octets libres

In [53]:
import pandas as pd

def get_header_row(file_path, keyword):
    try:
        df_temp = pd.read_excel(file_path, header=None, nrows=20)
        for idx, row in df_temp.iterrows():
            line_text = " ".join(row.astype(str).values).lower()
            if keyword.lower() in line_text:
                return idx
        return 0
    except Exception:
        return 0

# --- Chargement ---
df_valene = pd.read_excel('source/Export Sotrema novembre 2025.xlsx', header=get_header_row('source/Export Sotrema novembre 2025.xlsx', 'N° de pesée'))
df_pap = pd.read_excel('source/VALENE PAP Novembre 2025.xlsx', header=get_header_row('source/VALENE PAP Novembre 2025.xlsx', 'Description'))
df_pav = pd.read_excel('source/VALENE PAV Novembre 2025.xls', header=get_header_row('source/VALENE PAV Novembre 2025.xls', 'Description'))
df_sotrema2 = pd.read_excel('source/VALENE SOTREMA2 Novembre 2025.xlsx', header=get_header_row('source/VALENE SOTREMA2 Novembre 2025.xlsx', 'Description'))

In [54]:
df_pap.to_excel('test.xlsx', index=False)

In [55]:
##df_valene = df_valene.iloc[9:]

In [56]:
df_valene.head()

,N° de pesée,Occurence,Date d'entrée,Heure d'entrée,Date de sortie,Heure de sortie,Sens,Petite Bascule,Pesée Porteur,Site de pesage,Code client,Client,Commande,Commande client,Code transporteur,Transporteur,Tiers Apporteur,Commande transport,Code regroupement,Regroupement,Code lieu d'exploitation,Lieu d'exploitation,Lieu d'enlèvement libre,Lieu de mise en oeuvre,Origine,Lieu d'exploitation de collecte,Service TVT,Code exutoire,Exutoire,Filière,Zone,Immatriculation,Volume,Poids de la matière,Caissier,Id matière annoncée,Code matière annoncée,Matière annoncée,Qualité matière annoncée,Id matière réalisée,Code matière réalisée,Matière réalisée,Qualité matière réalisée,Sous contenant,Nombre de Sous-contenants,Matière budget,Groupe M1,Groupe M2,Date de création,Heure de création,Date de modification,Heure de modification,Référence,Poids récupéré en entrée,DSD entrée,Poids récupéré en sortie,DSD sortie,Type de saisie,Unité de mesure,Tonnage en entrée,Tonnage en sortie,Pont d'entrée,Pont de sortie,Quantité,Unité,Badge,Matière attendue,Chauffeur,Déclassement,Eclatement,% réfaction,Motif déclassement,Note qualité,Outil pesage,Indice radioactivité,Respects consignes,Abandon,Raison de l'abandon,Transfert Collecte,Date,Heure,Tentatives,Transfert TVT,Date.1,Heure.1,Tentatives.1,Entité de facturation,Entité de collecte,Bloquée,Compte de facturation,Nom du compte de facturation,Ville du producteur,Code postal du producteur,Commune du producteur,Utilisateur PDA,CAP/DIP/DAP,N° lot,N° badge client,Pourcentage d'éclatement,Dernière modification,Motif,Tonnage client,Code matière réalisée.1,Commentaires,Commercial contrat,Client intragroupe,Poids net forcé,Num Fidelité,Transfert Interne,Filière Départ,Zone Départ,Filière Arrivée,Zone Arrivée,Mode d'enregistrement,Numéro BSD,Refus
0,83972,1,2025-11-01,09:29:28,2025-11-01,09:34:44,A,NaN,NaN,GENERIS GUERVILLE,1000042072,CU GRAND PARIS SEINE ET OISE - AUBE,NaN,NaN,7067,SOTREMA,NON,NaN,NaN,NaN,879846,MLJ CV/MARTRAITS/GASSI,NaN,NaN,NaN,NaN,4450572,C15744,GENERIS GUERVILLE TRSFTD,GENERIS GUERVILLE TRSFTD,ZONE OM,BZ849SG,NaN,1.12,NaN,651,ME0202,ORDURES MENAGERES,NaN,651,ME0202,ORDURES MENAGERES,NaN,Non,NaN,NaN,ORDURES MENAGERES RESIDUELLES,NaN,NaN,NaN,2025-11-01,09:34:44,NaN,VRAI,55554.0,VRAI,55555.0,Temps réel,tonne,8.90,7.78,NaN,NaN,NaN,NaN,2902042.0,NaN,NaN,FAUX,FAUX,100,NaN,NaN,NaN,NaN,FAUX,FAUX,NaN,FAUX,NaN,NaN,0,FAUX,NaN,NaN,NaN,GENERIS GUERVILLE,NaN,FAUX,14456848,VALOSEINE,AUBERGENVILLE,78410,NaN,NaN,NaN,NaN,NaN,100,SERVEUR,CREATION,NaN,651,NaN,HUET Guillaume,Non,Non,NaN,FAUX,NaN,NaN,NaN,NaN,Automatique,NaN,NaN
1,83973,1,2025-11-01,10:58:25,2025-11-01,11:02:58,A,NaN,NaN,GENERIS GUERVILLE,1000035925,SOTREMA - ROSNY SUR SEINE - SIEGE,NaN,NaN,7067,SOTREMA,NON,NaN,NaN,NaN,569054,SOTREMA ROSNY,NaN,NaN,NaN,NaN,1027495,C15744,GENERIS GUERVILLE TRSFTD,GENERIS GUERVILLE TRSFTD,ZONE OM,ES031AK,NaN,0.16,NaN,651,ME0202,ORDURES MENAGERES,NaN,651,ME0202,ORDURES MENAGERES,NaN,Non,NaN,NaN,ORDURES MENAGERES RESIDUELLES,NaN,NaN,NaN,2025-11-01,11:02:58,NaN,VRAI,55556.0,VRAI,55557.0,Temps réel,tonne,7.90,7.74,NaN,NaN,NaN,NaN,2934427.0,NaN,NaN,FAUX,FAUX,100,NaN,NaN,NaN,NaN,FAUX,FAUX,NaN,FAUX,NaN,NaN,0,FAUX,NaN,NaN,NaN,GENERIS GUERVILLE,NaN,FAUX,80871014,SOTREMA,ROSNY SUR SEINE,78710,NaN,NaN,NaN,NaN,NaN,100,SERVEUR,CREATION,NaN,651,NaN,HUET Guillaume,Non,Non,NaN,FAUX,NaN,NaN,NaN,NaN,Automatique,NaN,NaN
2,83974,1,2025-11-01,11:10:10,2025-11-01,11:16:36,A,NaN,NaN,GENERIS GUERVILLE,1000042072,CU GRAND PARIS SEINE ET OISE - AUBE,NaN,NaN,7067,SOTREMA,NON,NaN,NaN,NaN,879854,MLJ SECT 4,NaN,NaN,NaN,NaN,4450621,C15744,GENERIS GUERVILLE TRSFTD,GENERIS GUERVILLE TRSFTD,ZONE OM,FX345DJ,NaN,9.82,NaN,651,ME0202,ORDURES MENAGERES,NaN,651,ME0202,ORDURES MENAGERES,NaN,Non,NaN,NaN,ORDURES MENAGERES RESIDUELLES,NaN,NaN,NaN,2025-11-01,11:16:36,NaN,VRAI,55558.0,VRAI,55559.0,Temps réel,tonne,24.18,14.36,NaN,NaN,NaN,NaN,2926667.0,NaN,NaN,FAUX,FAUX,100,NaN,NaN,NaN,NaN,FAUX,FAUX,NaN,FAUX,NaN,NaN,0,FAUX,NaN,NaN,NaN,GENERIS GUERVILLE,NaN,FAUX,14456848,VALOSEINE,MANTES-LA-JOLIE,78200,NaN,NaN,NaN,NaN,NaN,100,SERVEUR,CREATION,NaN,651,NaN,HUET Guillaume,Non,Non,NaN,FAUX,NaN,NaN,NaN,NaN,Automatique,NaN,NaN
3,83975,1,2025-11-01,12:26:21,2025-11-01,12:31:22,A,NaN,NaN,GENERIS GUERVILLE,1000035925,SOTREMA - ROSNY SUR SEINE - SIEGE,NaN,NaN,7067,SOTREMA,NON,NaN,NaN,NaN,569054,SOTREMA ROSNY,NaN,NaN,NaN,NaN,1027495,C15744,GENERIS GUERVILLE TRSFTD,GENERIS GUERVILLE TRSFTD,ZONE OM,ES031AK,NaN,3.90,NaN,651,ME0202,ORDURES MENAGERES,NaN,651,ME0202,ORDURES MENAGERES,NaN,Non,NaN,NaN,ORDURES MENAGERES RESIDUELLES,NaN,NaN,NaN,2025-11-01,12:31:22,NaN,VRAI,55560.0,VRAI,55561.0,Temps réel,tonne,18.52,14.62,NaN,NaN,NaN,NaN,2934427.0,NaN,NaN,FAUX,FAUX,100,NaN,NaN,NaN,NaN,FAUX,FAUX,NaN,FAUX,NaN,NaN,0,FAUX,NaN,NaN,NaN,GENERIS GUERVILLE,NaN,FAUX,80871014,SOTREMA,ROSNY SUR SEINE,78710,NaN,NaN,NaN,NaN,NaN,100,SERVEUR,CREATION,NaN,651,NaN,HUET Guillaume,Non,Non,NaN,FAUX,NaN,NaN,NaN,NaN,Automatique,NaN,NaN
4,83976,1,2025-11-01,14:22:52,2025-11-01,14:27:52,A,NaN,NaN,GENERIS GUERVILLE,1000035925,SOTREMA - ROSNY SUR SEINE - SIEGE,NaN,NaN,7067,SOTREMA,NON,NaN,NaN,NaN,569054,SOTREMA ROSNY,NaN,NaN,NaN,NaN,1027495,C15744,GENERIS GUERVILLE TRSFTD,GENERIS GUERVILLE TRSFTD,ZONE OM,ES031AK,NaN,1.64,NaN,651,ME0202,ORDURES MENAGERES,NaN,651,ME0202,ORDURES MENAGERES,NaN,Non,NaN,NaN,ORDURES MENAGERES RESIDUELLES,NaN,NaN,NaN,2025-11-01,14:27:52,NaN,VRAI,55562.0,VRAI,55563.0,Temps réel,tonne,16.20,14.56,NaN,NaN,NaN,NaN,2934427.0,NaN,NaN,FAUX,FAUX,100,NaN,NaN,NaN,NaN,FAUX,FAUX,NaN,FAUX,NaN,NaN,0,FAUX,NaN,NaN,NaN,GENERIS GUERVILLE,NaN,FAUX,80871014,SOTREMA,ROSNY SUR SEINE,78710,NaN,NaN,NaN,NaN,NaN,100,SERVEUR,CREATION,NaN,651,NaN,HUET Guillaume,Non,Non,NaN,FAUX,NaN,NaN,NaN,NaN,Automatique,NaN,NaN

In [57]:
df_sotrema2['Num Ticket'].isna().sum()

np.int64(1351)

In [58]:
df_valene.shape

(591, 116)

In [59]:
df_pav.head()

,Date,Description,Jour,Num Ticket,Num Bon,Chauffeur,Immatriculation,numParc,NomClient,Poids Net,Poids en Tonnes
0,2025-11-03,Ordures Ménagères,lundi,83995.0,11250078.0,HARRACH,GZ-197-VJ,124.0,CU GPSO,10440,10.44
1,2025-11-03,Ordures Ménagères,lundi,84005.0,11251843.0,DJAU,CW-373-EV,75.0,CU GPSO,480,0.48
2,2025-11-03,Ordures Ménagères,lundi,84008.0,11250144.0,DHOYE,DJ-320-BK,83.0,CU GPSO,5840,5.84
3,2025-11-03,Ordures Ménagères,lundi,84025.0,11250078.0,HARRACH,GZ-197-VJ,124.0,CU GPSO,6780,6.78
4,2025-11-03,Ordures Ménagères,lundi,84026.0,11250144.0,DHOYE,DJ-320-BK,83.0,CU GPSO,5280,5.28

In [60]:
df_valene.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 591 entries, 0 to 590
Columns: 116 entries, N° de pesée to Refus
dtypes: datetime64[ns](3), float64(54), int64(14), object(45)
memory usage: 535.7+ KB

In [61]:
colonnes_a_changer = ['Num Ticket', 'Poids en Tonnes','Num Bon', 'Description']
df_pav = df_pav[colonnes_a_changer]
df_pap = df_pap[colonnes_a_changer]
df_sotrema2 = df_sotrema2[colonnes_a_changer]

In [62]:
df_pav_manquants = df_pav[df_pav['Num Ticket'].isna()]
df_pap_manquants = df_pap[df_pap['Num Ticket'].isna()]
df_manquants = pd.concat([df_pav_manquants, df_pap_manquants])
display(df_manquants)

,Num Ticket,Poids en Tonnes,Num Bon,Description
86,NaN,399.800,NaN,NaN
20,NaN,0.760,11250152.0,Ordures Ménagères
107,NaN,0.220,11250718.0,Ordures Ménagères
123,NaN,0.620,11250823.0,Ordures Ménagères
143,NaN,0.000,11250999.0,Déchets Industriels Banals en mélange
146,NaN,0.120,11254987.0,Ordures Ménagères
248,NaN,2.733,11254548.0,Verre
268,NaN,0.460,11252181.0,Emballages Ménagers Recyclables
283,NaN,0.063,11255281.0,Emballages Ménagers Recyclables
291,NaN,0.000,11252578.0,Ordures Ménagères
408,NaN,2318.195,NaN,NaN

In [63]:
df_pav = df_pav[df_pav['Description'].notna()]
df_pap = df_pap[df_pap['Description'].notna()]
df_sotrema2 = df_sotrema2[df_sotrema2['Description'].notna()]
df_pap[df_pap['Description'] == 'Verre']

    Num Ticket  Poids en Tonnes     Num Bon Description
17       84011            0.009  11250047.0       Verre
18       84044            8.620  11250046.0       Verre
59       84182            1.080  11250310.0       Verre
60       84187            1.340  11250310.0       Verre
61       84193            1.000  11250310.0       Verre
62       84194            0.900  11250310.0       Verre
79       84211            1.960  11252381.0       Verre
80       84245            0.080  11252833.0       Verre
220     125191            0.040  11255278.0       Verre
221      84752            6.820  11251480.0       Verre
248        NaN            2.733  11254548.0       Verre
266      84900            0.140  11255109.0       Verre
267      84901            1.860  11250940.0       Verre

In [64]:
df_sotrema2 = df_sotrema2.dropna(subset=['Num Ticket'])
df_pav = df_pav.dropna(subset=['Num Ticket'])
df_pap = df_pap.dropna(subset=['Num Ticket'])

In [65]:
df_pav['Source'] = 'PAV'
df_pap['Source'] = 'PAP'
df_sotrema2['Source'] = 'SOTREMA2'

In [66]:
df_concat = pd.concat([df_pav, df_pap, df_sotrema2])
# df_concat = pd.concat([df_pav, df_pap])
df_concat['Num Ticket'] = pd.to_numeric(df_concat['Num Ticket'], errors='coerce')
df_concat["Num_Ticket_Est_Vide"] = df_concat['Num Ticket'].isna()
display(df_concat[df_concat["Num_Ticket_Est_Vide"] == True])

,Num Ticket,Poids en Tonnes,Num Bon,Description,Source,Num_Ticket_Est_Vide
405,NaN,13.3,11253875.0,Ordures Ménagères,PAP,True

In [67]:
df_pap['Num Ticket'] = pd.to_numeric(df_pap['Num Ticket'], errors='coerce').astype('Int64')
df_pav['Num Ticket'] = pd.to_numeric(df_pav['Num Ticket'], errors='coerce').astype('Int64')
df_sotrema2['Num Ticket'] = pd.to_numeric(df_sotrema2['Num Ticket'], errors='coerce').astype('Int64')
df_NaN = df_concat[df_concat['Num Ticket'].isna()]
df_NaN = df_NaN.drop(columns=['Num_Ticket_Est_Vide'])
display(df_NaN)

     Num Ticket  Poids en Tonnes     Num Bon        Description Source
405         NaN             13.3  11253875.0  Ordures Ménagères    PAP

In [68]:
# df_sotrema2.head()

In [69]:
df_pap.head()

   Num Ticket  Poids en Tonnes     Num Bon        Description Source
0       83973             0.16  11250007.0  Ordures Ménagères    PAP
1       83974             9.82  11250006.0  Ordures Ménagères    PAP
2       83979             3.62  11250038.0  Ordures Ménagères    PAP
3       83982             0.54  11250052.0  Ordures Ménagères    PAP
4       83985             8.32  11250057.0  Ordures Ménagères    PAP

In [70]:
# df_sotrema2.info()

In [71]:
# df_sotrema2.head()

In [72]:
liste_df = [df_pav, df_pap,df_sotrema2]
# liste_df = [df_pav, df_pap]

df_kerlog = pd.concat(liste_df, ignore_index=True)

In [73]:
df_kerlog.head()

   Num Ticket  Poids en Tonnes     Num Bon        Description Source
0       83995            10.44  11250078.0  Ordures Ménagères    PAV
1       84005             0.48  11251843.0  Ordures Ménagères    PAV
2       84008             5.84  11250144.0  Ordures Ménagères    PAV
3       84025             6.78  11250078.0  Ordures Ménagères    PAV
4       84026             5.28  11250144.0  Ordures Ménagères    PAV

In [74]:
df_valene.head()

,N° de pesée,Occurence,Date d'entrée,Heure d'entrée,Date de sortie,Heure de sortie,Sens,Petite Bascule,Pesée Porteur,Site de pesage,Code client,Client,Commande,Commande client,Code transporteur,Transporteur,Tiers Apporteur,Commande transport,Code regroupement,Regroupement,Code lieu d'exploitation,Lieu d'exploitation,Lieu d'enlèvement libre,Lieu de mise en oeuvre,Origine,Lieu d'exploitation de collecte,Service TVT,Code exutoire,Exutoire,Filière,Zone,Immatriculation,Volume,Poids de la matière,Caissier,Id matière annoncée,Code matière annoncée,Matière annoncée,Qualité matière annoncée,Id matière réalisée,Code matière réalisée,Matière réalisée,Qualité matière réalisée,Sous contenant,Nombre de Sous-contenants,Matière budget,Groupe M1,Groupe M2,Date de création,Heure de création,Date de modification,Heure de modification,Référence,Poids récupéré en entrée,DSD entrée,Poids récupéré en sortie,DSD sortie,Type de saisie,Unité de mesure,Tonnage en entrée,Tonnage en sortie,Pont d'entrée,Pont de sortie,Quantité,Unité,Badge,Matière attendue,Chauffeur,Déclassement,Eclatement,% réfaction,Motif déclassement,Note qualité,Outil pesage,Indice radioactivité,Respects consignes,Abandon,Raison de l'abandon,Transfert Collecte,Date,Heure,Tentatives,Transfert TVT,Date.1,Heure.1,Tentatives.1,Entité de facturation,Entité de collecte,Bloquée,Compte de facturation,Nom du compte de facturation,Ville du producteur,Code postal du producteur,Commune du producteur,Utilisateur PDA,CAP/DIP/DAP,N° lot,N° badge client,Pourcentage d'éclatement,Dernière modification,Motif,Tonnage client,Code matière réalisée.1,Commentaires,Commercial contrat,Client intragroupe,Poids net forcé,Num Fidelité,Transfert Interne,Filière Départ,Zone Départ,Filière Arrivée,Zone Arrivée,Mode d'enregistrement,Numéro BSD,Refus
0,83972,1,2025-11-01,09:29:28,2025-11-01,09:34:44,A,NaN,NaN,GENERIS GUERVILLE,1000042072,CU GRAND PARIS SEINE ET OISE - AUBE,NaN,NaN,7067,SOTREMA,NON,NaN,NaN,NaN,879846,MLJ CV/MARTRAITS/GASSI,NaN,NaN,NaN,NaN,4450572,C15744,GENERIS GUERVILLE TRSFTD,GENERIS GUERVILLE TRSFTD,ZONE OM,BZ849SG,NaN,1.12,NaN,651,ME0202,ORDURES MENAGERES,NaN,651,ME0202,ORDURES MENAGERES,NaN,Non,NaN,NaN,ORDURES MENAGERES RESIDUELLES,NaN,NaN,NaN,2025-11-01,09:34:44,NaN,VRAI,55554.0,VRAI,55555.0,Temps réel,tonne,8.90,7.78,NaN,NaN,NaN,NaN,2902042.0,NaN,NaN,FAUX,FAUX,100,NaN,NaN,NaN,NaN,FAUX,FAUX,NaN,FAUX,NaN,NaN,0,FAUX,NaN,NaN,NaN,GENERIS GUERVILLE,NaN,FAUX,14456848,VALOSEINE,AUBERGENVILLE,78410,NaN,NaN,NaN,NaN,NaN,100,SERVEUR,CREATION,NaN,651,NaN,HUET Guillaume,Non,Non,NaN,FAUX,NaN,NaN,NaN,NaN,Automatique,NaN,NaN
1,83973,1,2025-11-01,10:58:25,2025-11-01,11:02:58,A,NaN,NaN,GENERIS GUERVILLE,1000035925,SOTREMA - ROSNY SUR SEINE - SIEGE,NaN,NaN,7067,SOTREMA,NON,NaN,NaN,NaN,569054,SOTREMA ROSNY,NaN,NaN,NaN,NaN,1027495,C15744,GENERIS GUERVILLE TRSFTD,GENERIS GUERVILLE TRSFTD,ZONE OM,ES031AK,NaN,0.16,NaN,651,ME0202,ORDURES MENAGERES,NaN,651,ME0202,ORDURES MENAGERES,NaN,Non,NaN,NaN,ORDURES MENAGERES RESIDUELLES,NaN,NaN,NaN,2025-11-01,11:02:58,NaN,VRAI,55556.0,VRAI,55557.0,Temps réel,tonne,7.90,7.74,NaN,NaN,NaN,NaN,2934427.0,NaN,NaN,FAUX,FAUX,100,NaN,NaN,NaN,NaN,FAUX,FAUX,NaN,FAUX,NaN,NaN,0,FAUX,NaN,NaN,NaN,GENERIS GUERVILLE,NaN,FAUX,80871014,SOTREMA,ROSNY SUR SEINE,78710,NaN,NaN,NaN,NaN,NaN,100,SERVEUR,CREATION,NaN,651,NaN,HUET Guillaume,Non,Non,NaN,FAUX,NaN,NaN,NaN,NaN,Automatique,NaN,NaN
2,83974,1,2025-11-01,11:10:10,2025-11-01,11:16:36,A,NaN,NaN,GENERIS GUERVILLE,1000042072,CU GRAND PARIS SEINE ET OISE - AUBE,NaN,NaN,7067,SOTREMA,NON,NaN,NaN,NaN,879854,MLJ SECT 4,NaN,NaN,NaN,NaN,4450621,C15744,GENERIS GUERVILLE TRSFTD,GENERIS GUERVILLE TRSFTD,ZONE OM,FX345DJ,NaN,9.82,NaN,651,ME0202,ORDURES MENAGERES,NaN,651,ME0202,ORDURES MENAGERES,NaN,Non,NaN,NaN,ORDURES MENAGERES RESIDUELLES,NaN,NaN,NaN,2025-11-01,11:16:36,NaN,VRAI,55558.0,VRAI,55559.0,Temps réel,tonne,24.18,14.36,NaN,NaN,NaN,NaN,2926667.0,NaN,NaN,FAUX,FAUX,100,NaN,NaN,NaN,NaN,FAUX,FAUX,NaN,FAUX,NaN,NaN,0,FAUX,NaN,NaN,NaN,GENERIS GUERVILLE,NaN,FAUX,14456848,VALOSEINE,MANTES-LA-JOLIE,78200,NaN,NaN,NaN,NaN,NaN,100,SERVEUR,CREATION,NaN,651,NaN,HUET Guillaume,Non,Non,NaN,FAUX,NaN,NaN,NaN,NaN,Automatique,NaN,NaN
3,83975,1,2025-11-01,12:26:21,2025-11-01,12:31:22,A,NaN,NaN,GENERIS GUERVILLE,1000035925,SOTREMA - ROSNY SUR SEINE - SIEGE,NaN,NaN,7067,SOTREMA,NON,NaN,NaN,NaN,569054,SOTREMA ROSNY,NaN,NaN,NaN,NaN,1027495,C15744,GENERIS GUERVILLE TRSFTD,GENERIS GUERVILLE TRSFTD,ZONE OM,ES031AK,NaN,3.90,NaN,651,ME0202,ORDURES MENAGERES,NaN,651,ME0202,ORDURES MENAGERES,NaN,Non,NaN,NaN,ORDURES MENAGERES RESIDUELLES,NaN,NaN,NaN,2025-11-01,12:31:22,NaN,VRAI,55560.0,VRAI,55561.0,Temps réel,tonne,18.52,14.62,NaN,NaN,NaN,NaN,2934427.0,NaN,NaN,FAUX,FAUX,100,NaN,NaN,NaN,NaN,FAUX,FAUX,NaN,FAUX,NaN,NaN,0,FAUX,NaN,NaN,NaN,GENERIS GUERVILLE,NaN,FAUX,80871014,SOTREMA,ROSNY SUR SEINE,78710,NaN,NaN,NaN,NaN,NaN,100,SERVEUR,CREATION,NaN,651,NaN,HUET Guillaume,Non,Non,NaN,FAUX,NaN,NaN,NaN,NaN,Automatique,NaN,NaN
4,83976,1,2025-11-01,14:22:52,2025-11-01,14:27:52,A,NaN,NaN,GENERIS GUERVILLE,1000035925,SOTREMA - ROSNY SUR SEINE - SIEGE,NaN,NaN,7067,SOTREMA,NON,NaN,NaN,NaN,569054,SOTREMA ROSNY,NaN,NaN,NaN,NaN,1027495,C15744,GENERIS GUERVILLE TRSFTD,GENERIS GUERVILLE TRSFTD,ZONE OM,ES031AK,NaN,1.64,NaN,651,ME0202,ORDURES MENAGERES,NaN,651,ME0202,ORDURES MENAGERES,NaN,Non,NaN,NaN,ORDURES MENAGERES RESIDUELLES,NaN,NaN,NaN,2025-11-01,14:27:52,NaN,VRAI,55562.0,VRAI,55563.0,Temps réel,tonne,16.20,14.56,NaN,NaN,NaN,NaN,2934427.0,NaN,NaN,FAUX,FAUX,100,NaN,NaN,NaN,NaN,FAUX,FAUX,NaN,FAUX,NaN,NaN,0,FAUX,NaN,NaN,NaN,GENERIS GUERVILLE,NaN,FAUX,80871014,SOTREMA,ROSNY SUR SEINE,78710,NaN,NaN,NaN,NaN,NaN,100,SERVEUR,CREATION,NaN,651,NaN,HUET Guillaume,Non,Non,NaN,FAUX,NaN,NaN,NaN,NaN,Automatique,NaN,NaN

In [75]:
colonnes_valene = ['N° de pesée', 'Poids de la matière', 'Date d\'entrée', 'Matière réalisée']
df_valene = df_valene[colonnes_valene]

In [76]:
df_valene.head()

   N° de pesée  Poids de la matière Date d'entrée   Matière réalisée
0        83972                 1.12    2025-11-01  ORDURES MENAGERES
1        83973                 0.16    2025-11-01  ORDURES MENAGERES
2        83974                 9.82    2025-11-01  ORDURES MENAGERES
3        83975                 3.90    2025-11-01  ORDURES MENAGERES
4        83976                 1.64    2025-11-01  ORDURES MENAGERES

In [77]:
df_valene = df_valene.rename(columns={'N° de pesée': 'Num Ticket', 'Poids de la matière': 'Poids en Tonnes'})

In [78]:
df = pd.merge(df_kerlog, df_valene, on='Num Ticket', suffixes=('_kerlog', '_valene'), how='inner')
df['Num Bon'] = df['Num Bon'].astype(int)
df['Date d\'entrée'] = pd.to_datetime(df['Date d\'entrée']).dt.date

print("Aperçu des données fusionnées (premières lignes) :")
display(df.head())

Aperçu des données fusionnées (premières lignes) :

,Num Ticket,Poids en Tonnes_kerlog,Num Bon,Description,Source,Poids en Tonnes_valene,Date d'entrée,Matière réalisée
0,83995,10.44,11250078,Ordures Ménagères,PAV,10.44,2025-11-03,ORDURES MENAGERES
1,84005,0.48,11251843,Ordures Ménagères,PAV,0.48,2025-11-03,ORDURES MENAGERES
2,84008,5.84,11250144,Ordures Ménagères,PAV,5.84,2025-11-03,ORDURES MENAGERES
3,84025,6.78,11250078,Ordures Ménagères,PAV,6.78,2025-11-03,ORDURES MENAGERES
4,84026,5.28,11250144,Ordures Ménagères,PAV,5.28,2025-11-03,ORDURES MENAGERES

In [79]:
df['Difference'] = df['Poids en Tonnes_kerlog'] - df['Poids en Tonnes_valene']
ecarts = df[df['Difference'].abs() > 0]

if not ecarts.empty:
    print(f"\nDes écarts significatifs ont été trouvés pour {len(ecarts)} enregistrements :")
    display(ecarts)
else:
    print("\nAucun écart significatif trouvé dans les 'Poids en Tonnes' entre df_kerlog et df_valene pour les 'Num Ticket' correspondants.")

print(f"\nNombre total d'enregistrements avec un 'Num Ticket' correspondant : {len(df)}")

print(f"\nLe taux de fiabilisation des enregistrements est de {round(1-(len(ecarts)/len(df)), 2)} %.")

Des écarts significatifs ont été trouvés pour 11 enregistrements :

,Num Ticket,Poids en Tonnes_kerlog,Num Bon,Description,Source,Poids en Tonnes_valene,Date d'entrée,Matière réalisée,Difference
93,83997,0.018,11250045,Ordures Ménagères,PAP,8.90,2025-11-03,ORDURES MENAGERES,-8.882
103,84011,0.009,11250047,Verre,PAP,2.44,2025-11-03,VERRE,-2.431
350,84942,0.004,11252175,Emballages Ménagers Recyclables,PAP,4.34,2025-11-20,EMBALLAGES MENAGERS RECUPERES,-4.336
353,84957,0.006,11252187,Emballages Ménagers Recyclables,PAP,6.14,2025-11-20,EMBALLAGES MENAGERS RECUPERES,-6.134
359,84974,0.003,11252588,Emballages Ménagers Recyclables,PAP,1.10,2025-11-21,EMBALLAGES MENAGERS RECUPERES,-1.097
380,85028,0.005,11252563,Ordures Ménagères,PAP,5.00,2025-11-21,ORDURES MENAGERES,-4.995
396,85101,0.009,11252993,Ordures Ménagères,PAP,8.80,2025-11-24,ORDURES MENAGERES,-8.791
399,85175,0.002,11253127,Emballages Ménagers Recyclables,PAP,2.38,2025-11-25,EMBALLAGES MENAGERS RECUPERES,-2.378
441,85244,0.008,11253407,Ordures Ménagères,PAP,8.40,2025-11-26,ORDURES MENAGERES,-8.392
452,85295,0.003,11253588,Emballages Ménagers Recyclables,PAP,3.08,2025-11-27,EMBALLAGES MENAGERS RECUPERES,-3.077
472,85335,0.011,11253878,Ordures Ménagères,PAP,11.46,2025-11-28,ORDURES MENAGERES,-11.449

Nombre total d'enregistrements avec un 'Num Ticket' correspondant : 567

Le taux de fiabilisation des enregistrements est de 0.98 %.

In [80]:
num_ticket_valene = set(df_valene['Num Ticket'].dropna())
num_ticket_kerlog = set(df['Num Ticket'].dropna())

num_ticket_manquant = num_ticket_valene - num_ticket_kerlog
num_ticket_manquant

len(num_ticket_manquant)

df.to_csv('verif_tonnage_resultat.csv', index=False)

In [81]:
df_bons_manquants = df_valene[df_valene['Num Ticket'].isin(num_ticket_manquant)].copy()

colonnes_a_afficher = ['Num Ticket', "Date d'entrée"]

cols_existantes = [c for c in colonnes_a_afficher if c in df_bons_manquants.columns]

df_bons_manquants['Date d\'entrée'] = pd.to_datetime(df_bons_manquants['Date d\'entrée']).dt.date

display(df_bons_manquants[cols_existantes])

     Num Ticket Date d'entrée
0         83972    2025-11-01
3         83975    2025-11-01
7         83984    2025-11-03
10        83991    2025-11-03
14        83998    2025-11-03
83        84172    2025-11-05
94        84195    2025-11-06
178       84399    2025-11-11
215       84492    2025-11-12
231       84528    2025-11-12
236       84536    2025-11-13
245       84557    2025-11-13
304       84706    2025-11-17
378       84888    2025-11-19
386       84906    2025-11-20
391       84917    2025-11-20
393       84923    2025-11-20
404       84949    2025-11-20
409       84960    2025-11-21
411       84966    2025-11-21
477       85121    2025-11-25
507       85190    2025-11-26
550       85280    2025-11-27
559       85305    2025-11-28
581       85365    2025-11-28
586       85376    2025-11-29

In [82]:
display(df[df['Num Ticket'] < 10000])
display(df)

Empty DataFrame
Columns: [Num Ticket, Poids en Tonnes_kerlog, Num Bon, Description, Source, Poids en Tonnes_valene, Date d'entrée, Matière réalisée, Difference]
Index: []

,Num Ticket,Poids en Tonnes_kerlog,Num Bon,Description,Source,Poids en Tonnes_valene,Date d'entrée,Matière réalisée,Difference
0,83995,10.44,11250078,Ordures Ménagères,PAV,10.44,2025-11-03,ORDURES MENAGERES,0.0
1,84005,0.48,11251843,Ordures Ménagères,PAV,0.48,2025-11-03,ORDURES MENAGERES,0.0
2,84008,5.84,11250144,Ordures Ménagères,PAV,5.84,2025-11-03,ORDURES MENAGERES,0.0
3,84025,6.78,11250078,Ordures Ménagères,PAV,6.78,2025-11-03,ORDURES MENAGERES,0.0
4,84026,5.28,11250144,Ordures Ménagères,PAV,5.28,2025-11-03,ORDURES MENAGERES,0.0
...,...,...,...,...,...,...,...,...,...
562,85281,1.56,11255114,Déchets Industriels Banals en mélange,SOTREMA2,1.56,2025-11-27,ORDURES MENAGERES,0.0
563,85382,2.02,11253886,Déchets Industriels Banals en mélange,SOTREMA2,2.02,2025-11-29,ORDURES MENAGERES,0.0
564,85347,6.82,11253944,Déchets Industriels Banals en mélange,SOTREMA2,6.82,2025-11-28,ORDURES MENAGERES,0.0
565,85307,0.22,11253894,Déchets Industriels Banals en mélange,SOTREMA2,0.22,2025-11-28,ORDURES MENAGERES,0.0
566,85383,1.48,11254231,Déchets Industriels Banals en mélange,SOTREMA2,1.48,2025-11-29,ORDURES MENAGERES,0.0

In [83]:
df_NaN.head()

     Num Ticket  Poids en Tonnes     Num Bon        Description Source
405         NaN             13.3  11253875.0  Ordures Ménagères    PAP

In [84]:
with pd.ExcelWriter('output/resultats.xlsx') as writer:
    ecarts.to_excel(writer, sheet_name='Ecart_Tonnage', index=False)
    df_bons_manquants.to_excel(writer, sheet_name='Bons_manquants', index=False)
    df_NaN.to_excel(writer, sheet_name='Num Ticket Non Conforme', index=False)